/**
 * The edge routing artifact for the public attachment prefix.
 *
 * `buildDeploymentPlan` describes the route order a shared hostname needs, but a
 * description is not deployable: on a hostname whose `*` route already belongs to
 * a shortlinks worker, `<host>/a/<token>` keeps resolving to that worker and every
 * server-hosted share link 404s. Cloudflare picks the *most specific* matching
 * route, so the fix is a real `<host><prefix>/*` route bound to a worker that
 * forwards to the attachments origin. This module renders that worker and its
 * `wrangler.toml` from the configured deployment metadata, and refuses to render
 * placeholders — an artifact containing `<attachments-origin>` deploys cleanly and
 * still leaves the prefix dead.
 */
import { buildDeploymentPlan } from "./deployment";
import { getConfig, type AttachmentsConfig } from "./config";

// Wrangler requires a compatibility date on every worker. Pinned rather than
// generated from `Date.now()` so re-rendering the artifact produces a stable
// diff instead of a spurious one on every run.
const WORKER_COMPATIBILITY_DATE = "2026-07-01";
const WORKER_NAME = "attachments-edge";

export interface EdgeRoute {
  pattern: string;
  zone_name: string;
  origin: string;
  purpose: string;
}

export interface EdgeRoutingArtifacts {
  worker_name: string;
  hostname: string;
  zone_name: string;
  path_prefix: string;
  routes: EdgeRoute[];
  environment: {
    ATTACHMENTS_ORIGIN: string;
    FALLBACK_ORIGIN: string;
    ATTACHMENTS_PATH_PREFIX: string;
  };
  wrangler_toml: string;
  worker_script: string;
}

export class EdgeRoutingConfigError extends Error {
  readonly missing: string[];

  constructor(missing: string[]) {
    super(
      `Edge routing configuration incomplete. Missing: ${missing.join(", ")}. ` +
        `Run 'attachments domain configure --hostname <hostname> --attachments-origin <url>' first.`
    );
    this.name = "EdgeRoutingConfigError";
    this.missing = missing;
  }
}

// Wrangler routes need the zone, which is not the hostname on a subdomain. Use
// the configured DNS zone when there is one and fall back to the registrable
// apex only as a hint the operator can correct in the emitted file.
function resolveZoneName(hostname: string, config: AttachmentsConfig): string {
  const configured = config.deployment.dns?.zone?.trim();
  if (configured) return configured;
  const labels = hostname.split(".").filter(Boolean);
  return labels.length > 2 ? labels.slice(-2).join(".") : hostname;
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function renderWorkerScript(pathPrefix: string, attachmentsOrigin: string, fallbackOrigin: string): string {
  return `// Generated by 'attachments domain render'. Do not edit by hand.
//
// Cloudflare matches the most specific route first, so the ${pathPrefix}/* route below
// wins over the generic <host>/* route that serves shortlinks. Everything outside
// the attachment prefix is handed back to the fallback origin unchanged.
const ATTACHMENTS_ORIGIN = ${JSON.stringify(attachmentsOrigin)};
const FALLBACK_ORIGIN = ${JSON.stringify(fallbackOrigin)};
const ATTACHMENTS_PATH_PREFIX = ${JSON.stringify(pathPrefix)};

export function resolveOrigin(pathname, env) {
  const prefix = (env && env.ATTACHMENTS_PATH_PREFIX) || ATTACHMENTS_PATH_PREFIX;
  const isAttachmentPath = pathname === prefix || pathname.startsWith(prefix + "/");
  if (isAttachmentPath) return (env && env.ATTACHMENTS_ORIGIN) || ATTACHMENTS_ORIGIN;
  return (env && env.FALLBACK_ORIGIN) || FALLBACK_ORIGIN;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const origin = resolveOrigin(url.pathname, env);
    if (!origin) {
      return new Response("No origin is configured for this route.", { status: 502 });
    }
    const target = new URL(url.pathname + url.search, origin);
    return fetch(new Request(target, request));
  },
};
`;
}

function renderWranglerToml(artifacts: Omit<EdgeRoutingArtifacts, "wrangler_toml" | "worker_script">): string {
  const routeBlocks = artifacts.routes
    .map(
      (route) =>
        `# ${route.purpose}\n[[routes]]\npattern = ${tomlString(route.pattern)}\nzone_name = ${tomlString(route.zone_name)}\n`
    )
    .join("\n");

  return `# Generated by 'attachments domain render'. Do not edit by hand.
#
# Route order matters: ${artifacts.routes[0]?.pattern} must stay more specific than the
# generic fallback so share links reach the attachments app instead of the
# shortlinks route that answers <host>/*.
name = ${tomlString(artifacts.worker_name)}
main = "worker.js"
compatibility_date = ${tomlString(WORKER_COMPATIBILITY_DATE)}

${routeBlocks}
[vars]
ATTACHMENTS_ORIGIN = ${tomlString(artifacts.environment.ATTACHMENTS_ORIGIN)}
FALLBACK_ORIGIN = ${tomlString(artifacts.environment.FALLBACK_ORIGIN)}
ATTACHMENTS_PATH_PREFIX = ${tomlString(artifacts.environment.ATTACHMENTS_PATH_PREFIX)}
`;
}

export function buildEdgeRoutingArtifacts(config: AttachmentsConfig = getConfig()): EdgeRoutingArtifacts {
  const plan = buildDeploymentPlan(config);
  if (plan.routing.missing.length > 0) throw new EdgeRoutingConfigError(plan.routing.missing);

  const hostname = plan.public_hostname!;
  const attachmentsOrigin = plan.routing.attachments_origin!;
  const fallbackOrigin = plan.routing.fallback_origin ?? "";
  const zoneName = resolveZoneName(hostname, config);

  const routes: EdgeRoute[] = [
    {
      pattern: plan.routing.attachment_route_pattern,
      zone_name: zoneName,
      origin: attachmentsOrigin,
      purpose: "Serve open-attachments public pages and downloads ahead of the generic route",
    },
  ];

  // Only claim <host>/* when an explicit fallback origin exists. Binding the
  // catch-all without one would take the shortlinks traffic away from whatever
  // serves it today and answer it with a 502 — a wider outage than the one being
  // fixed. Without a fallback the single /a/* route is enough: Cloudflare leaves
  // every other path on the existing route.
  if (fallbackOrigin) {
    routes.push({
      pattern: plan.routing.fallback_route_pattern,
      zone_name: zoneName,
      origin: fallbackOrigin,
      purpose: "Hand non-attachment paths back to the existing shortlinks origin",
    });
  }

  const base = {
    worker_name: WORKER_NAME,
    hostname,
    zone_name: zoneName,
    path_prefix: plan.public_path,
    routes,
    environment: {
      ATTACHMENTS_ORIGIN: attachmentsOrigin,
      FALLBACK_ORIGIN: fallbackOrigin,
      ATTACHMENTS_PATH_PREFIX: plan.public_path,
    },
  };

  return {
    ...base,
    wrangler_toml: renderWranglerToml(base),
    worker_script: renderWorkerScript(plan.public_path, attachmentsOrigin, fallbackOrigin),
  };
}
